---
# Create secret with:
# oc create secret -n openshift-monitoring generic alertmanager-main --from-file=alertmanager.yaml=path/to/this/file.yaml
global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - match:
      alertname: DeadMansSwitch
    repeat_interval: 5m
    receiver: deadmansswitch
receivers:
- name: default
  webhook_configs:
  - url: http://prometheus-bigpanda-relay.openshift-monitoring.svc.cluster.local:8080/alert
- name: deadmansswitch
