---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bigpanda-dummy
  name: bigpanda-dummy
  namespace: openshift-monitoring
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bigpanda-dummy
  type: ClusterIP
